"""corrección

Revision ID: 25b4bb91bf86
Revises: 
Create Date: 2025-06-20 17:21:52.893081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25b4bb91bf86'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('nombre', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('imagenes',
    sa.Column('id_imagen', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('tipo_archivo', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id_imagen')
    )
    op.create_table('noticias',
    sa.Column('id_noticia', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('estado', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=60), nullable=True),
    sa.Column('introduccion', sa.String(length=200), nullable=True),
    sa.Column('contenido', sa.String(length=2000), nullable=True),
    sa.Column('imagen', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_noticia')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('nombre', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=60), nullable=True),
    sa.Column('apellido_usuario', sa.String(length=60), nullable=True),
    sa.Column('correo_usuario', sa.String(length=60), nullable=True),
    sa.Column('contrasena_usuario', sa.String(length=60), nullable=True),
    sa.Column('estado_editor', sa.Boolean(), nullable=True),
    sa.Column('estado_escritor', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('roles')
    op.drop_table('noticias')
    op.drop_table('imagenes')
    op.drop_table('categorias')
    # ### end Alembic commands ###
