"""foraneas

Revision ID: dc9109eb713d
Revises: 25b4bb91bf86
Create Date: 2025-06-20 17:23:53.230838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc9109eb713d'
down_revision: Union[str, None] = '25b4bb91bf86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentarios',
    sa.Column('id_comentario', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('contenido', sa.String(length=200), nullable=True),
    sa.Column('noticia_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['noticia_id'], ['noticias.id_noticia'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_comentario')
    )
    op.add_column('imagenes', sa.Column('noticia_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'imagenes', 'noticias', ['noticia_id'], ['id_noticia'])
    op.add_column('noticias', sa.Column('categoria_id', sa.Integer(), nullable=True))
    op.add_column('noticias', sa.Column('comentario_id', sa.Integer(), nullable=True))
    op.add_column('noticias', sa.Column('usuario_revisor_id', sa.Integer(), nullable=True))
    op.add_column('noticias', sa.Column('usuario_escritor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'noticias', 'comentarios', ['comentario_id'], ['id_comentario'])
    op.create_foreign_key(None, 'noticias', 'usuarios', ['usuario_escritor_id'], ['id_usuario'])
    op.create_foreign_key(None, 'noticias', 'usuarios', ['usuario_revisor_id'], ['id_usuario'])
    op.create_foreign_key(None, 'noticias', 'categorias', ['categoria_id'], ['id_categoria'])
    op.add_column('usuarios', sa.Column('rol_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usuarios', 'roles', ['rol_id'], ['id_rol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'rol_id')
    op.drop_constraint(None, 'noticias', type_='foreignkey')
    op.drop_constraint(None, 'noticias', type_='foreignkey')
    op.drop_constraint(None, 'noticias', type_='foreignkey')
    op.drop_constraint(None, 'noticias', type_='foreignkey')
    op.drop_column('noticias', 'usuario_escritor_id')
    op.drop_column('noticias', 'usuario_revisor_id')
    op.drop_column('noticias', 'comentario_id')
    op.drop_column('noticias', 'categoria_id')
    op.drop_constraint(None, 'imagenes', type_='foreignkey')
    op.drop_column('imagenes', 'noticia_id')
    op.drop_table('comentarios')
    # ### end Alembic commands ###
